# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import orderbooks_pb2 as orderbooks__pb2


class OrderBooksStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetExchanges = channel.unary_unary(
                '/orderbooks.OrderBooks/GetExchanges',
                request_serializer=orderbooks__pb2.EmptyMsg.SerializeToString,
                response_deserializer=orderbooks__pb2.GetExchangesResponseMsg.FromString,
                )
        self.QueryEvents = channel.unary_stream(
                '/orderbooks.OrderBooks/QueryEvents',
                request_serializer=orderbooks__pb2.EventsQueryMsg.SerializeToString,
                response_deserializer=orderbooks__pb2.SnapshotMsg.FromString,
                )
        self.GetLiveData = channel.unary_stream(
                '/orderbooks.OrderBooks/GetLiveData',
                request_serializer=orderbooks__pb2.EventsQueryMsg.SerializeToString,
                response_deserializer=orderbooks__pb2.SnapshotMsg.FromString,
                )


class OrderBooksServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetExchanges(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def QueryEvents(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetLiveData(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_OrderBooksServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetExchanges': grpc.unary_unary_rpc_method_handler(
                    servicer.GetExchanges,
                    request_deserializer=orderbooks__pb2.EmptyMsg.FromString,
                    response_serializer=orderbooks__pb2.GetExchangesResponseMsg.SerializeToString,
            ),
            'QueryEvents': grpc.unary_stream_rpc_method_handler(
                    servicer.QueryEvents,
                    request_deserializer=orderbooks__pb2.EventsQueryMsg.FromString,
                    response_serializer=orderbooks__pb2.SnapshotMsg.SerializeToString,
            ),
            'GetLiveData': grpc.unary_stream_rpc_method_handler(
                    servicer.GetLiveData,
                    request_deserializer=orderbooks__pb2.EventsQueryMsg.FromString,
                    response_serializer=orderbooks__pb2.SnapshotMsg.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'orderbooks.OrderBooks', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class OrderBooks(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetExchanges(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/orderbooks.OrderBooks/GetExchanges',
            orderbooks__pb2.EmptyMsg.SerializeToString,
            orderbooks__pb2.GetExchangesResponseMsg.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def QueryEvents(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/orderbooks.OrderBooks/QueryEvents',
            orderbooks__pb2.EventsQueryMsg.SerializeToString,
            orderbooks__pb2.SnapshotMsg.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetLiveData(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/orderbooks.OrderBooks/GetLiveData',
            orderbooks__pb2.EventsQueryMsg.SerializeToString,
            orderbooks__pb2.SnapshotMsg.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
